version: '3'
services:
  zookeeper:
    hostname: zookeeper
    platform: linux/amd64
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - for-alpha-net
  kafka:
    hostname: kafka
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    networks:
      - for-alpha-net
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    hostname: kafdrop
    platform: linux/amd64
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
      - "9000:9000"
    networks:
      - for-alpha-net
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - kafka
      - zookeeper
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    restart: always
    ports:
      - "3301:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Legend5!
      - MYSQL_DATABASE=test
    networks:
      - for-alpha-net

  redis:
    image: redis:latest
    container_name: my-redis-container
    restart: always
    ports:
      - "6371:6379"
    networks:
      - for-alpha-net

  discovery-service:
    image: lsb8375/test-discovery-service:2.0
    container_name: discovery-service
    ports:
      - "8761:8761"
    restart: always
    networks:
      - for-alpha-net

  gateway-service:
    image: lsb8375/test-gateway-service:2.0
    container_name: gateway-service
    ports:
      - "8000:8000"
    depends_on:
      - discovery-service
    restart: always
    networks:
      - for-alpha-net

  user-service:
    image: lsb8375/test-user-service:3.7
    container_name: user-service
    ports:
      - "8001:8001"
    depends_on:
      - discovery-service
      - gateway-service
      - mysql
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Legend5!
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: always
    networks:
      - for-alpha-net
  # foralpha-service: ports:8002:8002
networks:
  for-alpha-net:
