server:
  port: 8002

spring:
  config:
    import:
      - classpath:/config/openApi.yml
      - classpath:/config/data.yml

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
    show-sql: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG