server:
  port: 8002

spring:
  config:
    import:
      - classpath:/config/openApi.yml
      - classpath:/config/data.yml
      -
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP-SERVERS}

  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_DATASOURCE_DDL-AUTO}
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
    show-sql: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG

profiles:
  active: dev

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${INSTANCE_HOST}


