spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foralpha?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qlalfqjsgh
    driver-class-name: com.mysql.cj.jdbc.Driver