spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pda_project?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url : ${SPRING_DATASOURCE_URL}
    username: boyoung
    password: boyoung0903
    driver-class-name: com.mysql.cj.jdbc.Driver
