openapi:
  appkey: ${api_appkey}
  appsecretkey: ${api_appsecret}
cloud:
  aws:
    credentials:
      access-key: ${aws_accesskey}
      secret-key: ${aws_secretkey}
    region:
      static: ${region}
    s3:
      bucket: ${bucket}
    stack:
      auto: false