openapi:
  appkey: PSCjadYrwNhF5oaDn8A4g9Gof1o0qBvo6V5M
  appsecretkey: ptqAmWD9Kk+9SEQ2ZEF0acHmJOVETOOoHyL3JMVM59/h316Hbxt87OHCl85ym9XEw9G/jbEbmrqrEaynutSpHfMzWoEPtRxys/l4SouokdDemOaJvBQLhzyLZunmW7cX7n9JyvlcneFE4XPFX/OV0oE7CrM3G7U6P6G24SwuLBsvGQxGw7M=
